name: "Run SDK Bun Runtime Tests"
description: |
  Run the SDK examples with Bun runtime against local testnet

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node-pnpm

    # Install Bun
    - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # pin@v2
      with:
        bun-version: latest

    # Run package install. If install fails, it probably means the updated lockfile was
    # not included in the commit.
    - run: pnpm install --frozen-lockfile
      shell: bash
    # Build the SDK for use in the examples
    - run: pnpm build
      shell: bash

    # Run a local testnet in the background.
    - run: pnpm exec aptos node run-local-testnet --force-restart --assume-yes --with-indexer-api --log-to-stdout >& ${{ runner.temp }}/local-testnet-logs.txt &
      shell: bash

    # Wait for the local testnet to be ready by hitting the readiness endpoint.
    - run: |
        for _ in {1..80}; do
          if curl --fail --silent --show-error --max-time 120 http://127.0.0.1:8070 >/dev/null; then
            exit 0
          fi
          sleep 1.5
        done
        exit 1
      shell: bash

    # Run the Bun tests
    - uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # pin@v3
      name: bun-sdk-tests
      env:
        TMPDIR: ${{ runner.temp }}
        APTOS_NETWORK: local
      with:
        max_attempts: 3
        timeout_minutes: 15
        command: |
          cd examples/bun-test
          bun install
          bun run test:all

    - name: Print local testnet logs on failure
      shell: bash
      if: failure()
      run: |
        echo "::group::Local testnet logs"
        cat ${{ runner.temp }}/local-testnet-logs.txt
        echo "::endgroup::"

