name: "Lint SDK Code"
description: |
  Run Biome linter on the codebase to ensure consistency

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node-pnpm

    # Run Biome linter
    - run: pnpm install --frozen-lockfile && pnpm lint
      shell: bash
