packages:
  - packages/*
catalog:
  "@noble/curves": "^1.9.0"
  "@noble/hashes": "^1.5.0"
  "@scure/bip32": "^1.4.0"
  "@scure/bip39": "^1.3.0"
  "eventemitter3": "^5.0.1"
  "js-base64": "^3.7.7"
  "jwt-decode": "^4.0.0"
  "poseidon-lite": "^0.2.0"