import { defineConfig } from "vitest/config";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    setupFiles: [path.resolve(__dirname, "tests/setupDotenv.ts")],
    globalSetup: [path.resolve(__dirname, "tests/preTest.ts")],
    include: ["tests/**/*.test.ts"],
    exclude: ["dist/**", "examples/**", "confidential-asset/**"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      reporter: ["text", "html", "clover", "json", "lcov"],
      exclude: [
        "tests/**",
        // Generated GraphQL + query code; regenerated by `pnpm indexer-codegen`.
        "src/internal/queries/**",
        "src/types/generated/**",
        // Node-only CLI surface (child-process driven); exercised by integration
        // suites under `examples/`, not by the unit/e2e runner.
        "src/cli/**",
        // Bundler shim — no runtime behavior to cover.
        "src/utils/normalizeBundle.ts",
        // Long-running event-loop driver; covered behaviorally by the
        // `tests/e2e/transactionManagement/asyncQueue.test.ts` integration test.
        // Unit-mocking the timers would test the mock, not the queue.
        "src/transactions/management/asyncQueue.ts",
        // Re-export barrels and constants — no branches to cover.
        "src/index.ts",
        "src/version.ts",
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
    pool: "forks",
    maxWorkers: 4,
    testTimeout: 30000,
    hookTimeout: 120000,
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx", ".json"],
  },
});
