import { defineConfig } from "vitest/config";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Default Vitest config for offline / unit-style runs.
 *
 * Localnet e2e lives in `vitest.config.e2e.ts` and is excluded here so a bare
 * `vitest run` does not try to hit a node that was never started. Prefer
 * `pnpm test` (unit parallel, then e2e sequential) or `pnpm unit-test` /
 * `pnpm e2e-test` directly.
 */
export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    setupFiles: [path.resolve(__dirname, "tests/setupDotenv.ts")],
    include: ["tests/unit/**/*.test.ts"],
    exclude: ["dist/**", "examples/**", "confidential-asset/**", "tests/e2e/**"],
    coverage: {
      provider: "v8",
      include: ["src/**/*.ts"],
      reporter: ["text", "html", "clover", "json", "lcov"],
      exclude: [
        "tests/**",
        // Generated GraphQL + query code; regenerated by `pnpm indexer-codegen`.
        "src/internal/queries/**",
        "src/types/generated/**",
        // Node-only CLI surface (child-process driven); exercised by integration
        // suites under `examples/`, not by the unit/e2e runner.
        "src/cli/**",
        // Bundler shim — no runtime behavior to cover.
        "src/utils/normalizeBundle.ts",
        // Long-running event-loop driver; covered behaviorally by the
        // `tests/e2e/transactionManagement/asyncQueue.test.ts` integration test.
        // Unit-mocking the timers would test the mock, not the queue.
        "src/transactions/management/asyncQueue.ts",
        // Event-loop worker covered by tests/e2e/transactionManagement/transactionWorker.test.ts.
        "src/transactions/management/transactionWorker.ts",
        // Thin EventEmitter wrapper over TransactionWorker; e2e-covered.
        "src/api/transactionSubmission/management.ts",
        // Complex keyless account surface covered by keyless unit + e2e tests.
        "src/account/AbstractKeylessAccount.ts",
        // Re-export barrels and constants — no branches to cover.
        "src/index.ts",
        "src/version.ts",
      ],
      thresholds: {
        branches: 85,
        functions: 85,
        lines: 95,
        statements: 85,
      },
    },
    pool: "forks",
    maxWorkers: 4,
    testTimeout: 30000,
    hookTimeout: 120000,
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx", ".json"],
  },
});
