name: "Check SDK versions match"
description: |
  Run check-version to ensure versions match when the target branch is main

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v4

    # Run version check
    - run: pnpm check-version
      shell: bash
