name: "Check SDK versions match"
description: |
  Run check-version to ensure versions match when the target branch is main

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # pin@v6.5.0
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # pin@v6.1.0

    # Run version check
    - run: pnpm check-version
      shell: bash
