name: "Verify SDK formatting"
description: |
  Run prettier on the codebase to ensure consistency

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: 8.9.0

    # Verify that the format is correct
    - run: pnpm install --frozen-lockfile && pnpm _fmt --check
      shell: bash
