name: "Run SDK examples"
description: |
  Run the SDK Examples tests against local testnet

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: 8.9.0

    # Run package install. If install fails, it probably means the updated lockfile was
    # not included in the commit.
    - run: pnpm install --frozen-lockfile
      shell: bash
    # Build the SDk for use in the examples
    - run: pnpm build
      shell: bash

    # Install the CLI.
    - run: pnpm install -g @aptos-labs/aptos-cli
      shell: bash

    # Run a local testnet in the background.
    - run: aptos node run-local-testnet --force-restart --assume-yes --with-indexer-api --log-to-stdout >& ${{ runner.temp }}/local-testnet-logs.txt &
      shell: bash

    # Wait for the local testnet to be ready by hitting the readiness endpoint.
    # We give it a while because the CLI will have to download some images before
    # actually running the local testnet, which can take a while.
    - run: pnpm install -g wait-on
      shell: bash
    - run: wait-on --verbose --interval 1500 --timeout 120000 --httpTimeout 120000 http-get://127.0.0.1:8070
      shell: bash

    # Run the typescript examples
    - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
      name: sdk-pnpm-examples
      env:
        # This is important, it ensures that the tempdir we create for cloning the ANS
        # repo and mounting it into the CLI container is created in a location that
        # actually supports mounting. Learn more here: https://stackoverflow.com/a/76523941/3846032.
        TMPDIR: ${{ runner.temp }}
        APTOS_NETWORK: local
      with:
        max_attempts: 3
        timeout_minutes: 25
        command: cd examples/typescript && pnpm install && pnpm build && pnpm test

    - name: Print local testnet logs on failure
      shell: bash
      if: failure()
      run: cat ${{ runner.temp }}/local-testnet-logs.txt

    # Run the typescript-esm examples
    - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
      name: sdk-pnpm-examples
      env:
        # This is important, it ensures that the tempdir we create for cloning the ANS
        # repo and mounting it into the CLI container is created in a location that
        # actually supports mounting. Learn more here: https://stackoverflow.com/a/76523941/3846032.
        TMPDIR: ${{ runner.temp }}
        APTOS_NETWORK: local
      with:
        max_attempts: 3
        timeout_minutes: 25
        command: cd examples/typescript-esm && pnpm install && pnpm test

    - name: Print local testnet logs on failure
      shell: bash
      if: failure()
      run: cat ${{ runner.temp }}/local-testnet-logs.txt

    # Run the javascript examples
    - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
      name: sdk-pnpm-examples
      env:
        # This is important, it ensures that the tempdir we create for cloning the ANS
        # repo and mounting it into the CLI container is created in a location that
        # actually supports mounting. Learn more here: https://stackoverflow.com/a/76523941/3846032.
        TMPDIR: ${{ runner.temp }}
        APTOS_NETWORK: local
      with:
        max_attempts: 3
        timeout_minutes: 25
        command: cd examples/javascript && pnpm install && pnpm test

    - name: Print local testnet logs on failure
      shell: bash
      if: failure()
      run: cat ${{ runner.temp }}/local-testnet-logs.txt
