name: "Run SDK E2E tests"
description: |
  Run the SDK E2E tests against a local testnet from the latest Aptos CLI

# Currently no indexer tests or tests against local testnets from production branches,
# we just use whatever is in the latest CLI.

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: 8.9.0

    # Run package install. If install fails, it probably means the updated lockfile was
    # not included in the commit.
    - run: pnpm install --frozen-lockfile
      shell: bash

    # Install the CLI.
    - run: pnpm install -g @aptos-labs/aptos-cli
      shell: bash

    # Run a local testnet in the background.
    - run: aptos node run-local-testnet --force-restart --assume-yes --with-faucet &
      shell: bash

    # Use this instead when the new CLI lands.
    # - run: aptos node run-local-testnet --force-restart --assume-yes --with-indexer-api &

    # Wait for the local testnet to be ready by hitting the readiness endpoint.
    - run: pnpm install -g wait-on
      shell: bash
    - run: wait-on -t 60000 --httpTimeout 60000 http-get://127.0.0.1:8081
      shell: bash

    # Use this instead when the new CLI lands.
    # - run: wait-on -t 60000 --httpTimeout 60000 http-get://127.0.0.1:8070

    # Run the TS SDK tests.
    - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
      name: sdk-pnpm-test
      env:
        # This is important, it ensures that the tempdir we create for cloning the ANS
        # repo and mounting it into the CLI container is created in a location that
        # actually supports mounting. Learn more here: https://stackoverflow.com/a/76523941/3846032.
        TMPDIR: ${{ runner.temp }}
      with:
        max_attempts: 3
        timeout_minutes: 25
        command: pnpm run test
