name: "SDK Unit Tests"
description: |
  Run the SDK unit tests locally

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: 8.9.0

    # Run unit tests
    - run: pnpm install --frozen-lockfile && pnpm unit-test
      shell: bash
