name: "Run optimized SDK build"
description: |
    Run build for Browser, Node, and Types

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v2
      with:
        version: 8.9.0

    # Run package install and build
    - run: pnpm install --frozen-lockfile && pnpm build
      shell: bash
