name: "Run optimized SDK build"
description: |
    Run build for Browser, Node, and Types

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-node-pnpm

    # Run package install, build, and license checks
    - run: pnpm install --frozen-lockfile && pnpm build && pnpm check-license
      shell: bash
