name: "Run SDK E2E tests"
description: |
  Run the SDK E2E tests against a local testnet from the latest Aptos CLI

# Currently no indexer tests or tests against local testnets from production branches,
# we just use whatever is in the latest CLI.

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v4

    # Run package install. If install fails, it probably means the updated lockfile was
    # not included in the commit.
    - run: pnpm install --frozen-lockfile
      shell: bash

    # Run the TS SDK tests.
    - uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # pin@v3
      name: sdk-pnpm-test
      env:
        # This is important, it ensures that the tempdir we create for cloning the ANS
        # repo and mounting it into the CLI container is created in a location that
        # actually supports mounting. Learn more here: https://stackoverflow.com/a/76523941/3846032.
        TMPDIR: ${{ runner.temp }}
      with:
        max_attempts: 3
        timeout_minutes: 25
        # This runs all the tests, both unit and e2e.
        command: pnpm run test

    - name: Print local testnet logs on failure
      shell: bash
      if: failure()
      run: cat ${{ runner.temp }}/local-testnet-logs.txt
