name: "Run build and unit tests on Windows"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-windows-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/run-build
      - uses: ./.github/actions/run-unit-tests
